### PR TITLE
Topology name accessor

### PR DESCRIPTION
**Pull request by dennisklein**
Related to #230

### CODE REVIEW

**Comment by AndreyLebedev** [comment]
@dennisklein I have a couple of comments regarding this pull request.
1) What is the use case of topology name? We actually plan to remove this attribute in the next releases. If you need to get the currently active topology I propose to get the file path instead of the topology name. Path to a topology file is a more general solution because you can query any static attributes of the topology via the CTopology interface and not via dds-info.

2) m_hasActiveTopology attribute looks a bit misleading. It depends on how you define an active topology. I think a better solution is to introduce an additional option to "dds-info -n" so that one can get the number of agents with a certain state, e.g. "dds-info -n idle" will return number of idle agents. And of cause the same interface for tools-api. 
We are also thinking of implementing more advanced queries for dds-info, but this will certainly take more time to implement.

I propose to close this pull request. We will implement the proposed changes asap.

**Comment by dennisklein** [comment]
> 1. What is the use case of topology name? We actually plan to remove this attribute in the next releases. If you need to get the currently active topology I propose to get the file path instead of the topology name. Path to a topology file is a more general solution because you can query any static attributes of the topology via the CTopology interface and not via dds-info.

Please do not remove it. It is essential. The xml file is just a local serialized representation of a topology. The filename/path is a pure local property. One could easily have the same topology under multiple filenames or just as temporary/volatile files.

The use case is easy: When you attach to an existing session, you have no idea which topology the session is executing (or if any at all). How are you supposed to match it to a topology xml spec lying around on your hard disk?

Let me be clear, I don't care, if I can specify a custom name a topology. I care about being able to query the server for a handle/id/whatever that I can also locally extract (either just read an xml attribute/element value or compute some hash from the topology spec).

> 2. m_hasActiveTopology attribute looks a bit misleading. It depends on how you define an active topology.

I defined it as proposed, if any agent in the session is still executing anything, the topology is active. You even use the same terminology in your updateTopology handler in the commander.

> I think a better solution is to introduce an additional option to "dds-info -n" so that one can get the number of agents with a certain state, e.g. "dds-info -n idle" will return number of idle agents. And of cause the same interface for tools-api.

This is what I proposed long ago and it would be awesome to have in addition, see #180:
"As a developer of higher level tools that use DDS in their backends, I would like to use event subscription APIs to a multitude of events regarding DDS objects such as Commander, Agents, Tasks etc (object created, online, crashed etc). This will allow much cleaner and much more efficient implementations on my side."

---

To illustrate more the use case, let me give you another example: Imagine you wanted to implement an object inspector widget for DDS, similar to this one:

worddav331a04a5c74c9761a96e3a1f77ded163

Now in the dropdown box you would e.g. see a list of sessions, when selecting one, you see among other things if it currently executes a topology and which. In addition, one would want to show an up-to-date list of objects that live and can be inspected. Being able to do an agentInfo/commanderInfo request is the bare minimum. You wouldn't want to make 10 of those requests per second just that my client view stays up to date, would you? I am looking for an observer pattern here (which you have within a single request, but not on upper levels of your state). E.g. I would like to attach to a running session, query it for its complete state (even learn its full executing topology without having any spec in a file) and also observe events like a topology activation, update, expiration, user termination - same thing for the lifetimes of agents, tasks etc.

**Comment by dennisklein** [comment]
In just another words: I am looking for CRUD completeness (Create/Read/Update/Delete).

| DDS object | Create | Read | Update | Delete |
| --- | --- | --- | ---|
| session | `dds-session start` | `dds-session list` | - | `dds-session stop` |
| agent | `dds-submit` | `dds-info list` | `dds-submit` (add only) | only indirectly, but fine |
| topology | `dds-topology --activate` | **gap filled by this PR** | `dds-topology --update` | `dds-topology --stop` |
| task | - | `dds-info list` | - | - |

Since tasks are owned by an active topology, it is fine not being able to manipulate them directly. The other cells where I put `-` are fine as well at the moment. If you want, the proposed `dds-topology --active-topology` is the *list* for the topology.

**Comment by dennisklein** [comment]
To use the words of others to describe what I mean, see https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#object-spec-and-status. In DDS the topology xml file is the *object spec* and the active topology in a given session the *object status*.

See the metadata section: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#objects. `<topology name="MyTopology">` would be similar to their `name` metadata. One benefit of being able to specify it as a user, is that you do not need to provide versioning out of the box. One could include versioning information in this name. So, please reconsider to not remove it. It is very good design and essential IMHO.

**Comment by AndreyLebedev** [comment]
@dennisklein 

1)
> I defined it as proposed, if any agent in the session is still executing anything, the topology is active. You even use the same terminology in your updateTopology handler in the commander:

This is our internal implementation. We do not expose this definition to the user. For the user, the active topology is set during the activation of the topology with "dds-topology --activate". If the topology was ever activated and not stoped after that means that topology is active, i.e. it has a name in your implementation. If the topology has never been activated the name is an empty string.
If you want to check if there are any executing tasks in the topology it's better to directly query this information.

2) In your table, you mention CRUD, in my understanding for reading the topology it has to be something like "dds-topology --get" which will return the path to a topo file. Then it is consistent with "create" and "update" of the topology which take file path as an argument.

>The use case is easy: When you attach to an existing session, you have no idea which topology the session is executing (or if any at all). How are you supposed to match it to a topology xml spec lying around on your hard disk?

In case of a file path, the name of the topology file is similar to a topology name which you define in XML. For example, you can encode a version in the filename in the same way as in the XML.

**Comment by dennisklein** [comment]
@AndreyLebedev I removed the hasActiveTopology field as discussed and also changed the logic to the new definition of active topology as discussed, see the [changes](https://github.com/FairRootGroup/DDS/compare/5f806187b9e75387e494a08e6958a539c69e0417..6a87dd18522827ba4c200d431986b57c88ce3603). Remaining question would be, do you want to move the request from `dds-info --active-topology` to `dds-topology --get`? Consider that this PR also adds a `dds-topology --topology-name <topo.xml>` signature. Only reason I put it in `dds-info` is that it already performs a commander info request, so it was minimal changes. But if you want, I can move it to `dds-topology --get` or anything else?

**Comment by AndreyLebedev** [comment]
@dennisklein We can leave the implementation as it is now. If we find that there is a need to extend the request we can move the functionality later to dds-topology.

@AnarManafov Can you please merge this pull request?

**Comment by dennisklein** [comment]
Added another [small change](https://github.com/FairRootGroup/DDS/compare/6a87dd18522827ba4c200d431986b57c88ce3603..516251a4b8e56898b9c08152f718afe3e12f702d) to allow also `dds-topology --disable-validation --topology-name <topo.xml>`.

**Pull request merged**
