### PR TITLE
Modernize wn_bin

### PR DESCRIPTION
**Pull request by dennisklein**
~It is still missing a tiny bit (adding the test executable when building the tests).~ Anyways, let's discuss this next week or so. This would solve some problems we have currently when packaging DDS in Spack.

### CODE REVIEW

**Comment by AnarManafov** [comment]
@dennisklein , on OS X the wn_bin target fails with 
~~~~~
[100%] Generate WN binary package
CMake Error at /Users/anar/tmp/DDS/cmake/DDSCollectWNPkgFiles.cmake:10 (file):
  file Resolved path is not absolute
~~~~~

**Comment by dennisklein** [comment]
> @dennisklein , on OS X the wn_bin target fails with
> 
> ```
> [100%] Generate WN binary package
> CMake Error at /Users/anar/tmp/DDS/cmake/DDSCollectWNPkgFiles.cmake:10 (file):
>   file Resolved path is not absolute
> ```

Hm, would need more information.. Anyways, you are welcome to pick anything from this PR if it helps, does not need to have my name on it. I personally will probably not have the time to debug macOS on this topic.

**Comment by AnarManafov** [comment]
@dennisklein , I wouldn't close it.
I still want to figure out the seed of the problem and upgrade to cmake 3.16. We don't have much choice after all, as the current functions will be deprecated/removed at some point in anyway.

**Comment by AnarManafov** [comment]
I have cherry-pick'ed the RPATH-for-linux commit. The reset I will have to rework step by step to make it OS X compatible too.

**Pull request closed without merging**
